// import your files here e.g like this: import "./style.scss"
import "./style.scss"
import "./script/header"
import "./script/ToDo"
import "./script/karussel"
import "./script/strong"
import "./script/progress"
import "./script/theme"